### ISSUE TITLE
GData scope needed

### ISSUE THREAD

**Issue by jdar** [Scarygami/mirror-api#7]
Hi Gersham,

I'm getting an error accessing 'contacts' properties during login (see logs below) so I'm wondering what scopes you have in your client_secrets.json file. 
For contacts, I understand from documentation that we need GData scope https://developers.google.com/google-apps/contacts/v3/#authorizing_requests_to_the_api_name_service ("https://www.google.com/m8/feeds") ... which I thought should be added after line 89 in auth.py
            oauth_flow = flow_from_clientsecrets('client_secrets.json', scope='')

```
 Unfortunately, I haven't been able to get this to successfully work. So I'm punting this to the community.
```

My excerpt logs below for the 'connect' request.

Best,
Darius

URL being requested: https://wordambush.appspot.com/_ah/api/discovery/v1/apis/mirror/v1/rest?userIp=...
E2013-04-21 07:20:29.967
'Resource' object has no attribute 'contacts'
Traceback (most recent call last):
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in **call**
    rv = self.handle_exception(request, response, e)
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in **call**
    rv = self.router.dispatch(request, response)
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in **call**
    return handler.dispatch()
  File "/base/data/home/apps/s~wordambush/5.366831316248486240/utils.py", line 62, in dispatch
    webapp2.RequestHandler.dispatch(self)
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(_args, *_kwargs)
  File "/base/data/home/apps/s~wordambush/5.366831316248486240/auth.py", line 137, in post
    result = service.contacts().insert(body=body).execute()
AttributeError: 'Resource' object has no attribute 'contacts'
E2013-04-21 07:20:29.968
Traceback (most recent call last):
  File "/python27_runtime/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 223, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1519, in __call__
    response = self._internal_error(e)
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in **call**
    rv = self.router.dispatch(request, response)
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in **call**
    return handler.dispatch()
  File "/base/data/home/apps/s~wordambush/5.366831316248486240/utils.py", line 62, in dispatch
    webapp2.RequestHandler.dispatch(self)
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(_args, *_kwargs)
  File "/base/data/home/apps/s~wordambush/5.366831316248486240/auth.py", line 137, in post
    result = service.contacts().insert(body=body).execute()
AttributeError: 'Resource' object has no attribute 'contacts'

**Comment by Scarygami** [comment]
The "contacts" in this case have nothing to do with Google contacts but are the Mirror API Contacts.
For use of the cloud endpoints the oauth scope https://www.googleapis.com/auth/userinfo.email is the only necessary one, and this is requested client side, with a code sent to the server for exchange against access tokens.

The error you get is actually a weird one, because it seems the API Client wasn't generated correctly, even though the discovery document is available. Does this problem still persist, because I just tried on a fresh app engine project and didn't get that problem? Can you check in the app engine console in the DataStore viewer if a user entity with credentials was created?

(Also, the name is Gerwin...)

**Comment by jdar** [comment]
My apologies. I had a friend named Gersham.

On a fresh subdomain I confirm this works. I will try to clear out endpoints on the previous subdomain and figure out what permissions/settings are persisted and where.

Thank you for prompt reply!
